name: Build

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arduino-platform:
          - 'metro_m4_tinyusb'
          - 'pico_rp2040_tinyusb'

    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Checkout adafruit/ci-arduino
      uses: actions/checkout@v3
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: test platforms
      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }}
